const projects=[
{title:'Connecting identity to ServiceNow',category:'ServiceNow',className:'identity',tags:'ServiceNow · Microsoft Graph',symbols:['Entra','→','SN'],summary:'Bring identity data into service management with structured user provisioning.',challenge:'Keep user records aligned between enterprise identity and the service management platform.',approach:'Integrated Entra ID with ServiceNow using REST, Import Sets, and Transform Maps to populate user records. Configured SSO to align platform access with enterprise authentication.',outcome:'A structured integration for user data and authentication, supporting consistent service management records.'},
{title:'A repeatable employee lifecycle',category:'Automation',className:'automation',tags:'ADManager Plus · Entra ID',symbols:['Join','→','Exit'],summary:'Standardize onboarding and offboarding across hybrid identity and Microsoft 365.',challenge:'Account creation and deprovisioning involve multiple systems and need consistent execution.',approach:'Configured ADManager Plus onboarding and offboarding workflows covering account status, groups, licensing, mailbox conversion, and token revocation.',outcome:'Repeatable account lifecycle procedures with clearer execution steps across identity and messaging.'},
{title:'Intune inventory meets Active Directory',category:'Automation',className:'identity',tags:'Intune · Graph API · PowerShell',symbols:['Intune','→','AD'],summary:'Correlate mobile devices with directory users for actionable inventory.',challenge:'Mobile device inventory and directory user attributes were maintained in separate systems.',approach:'Queried Intune with Microsoft Graph, matched users, selected devices using freshness and device-type rules, and wrote phone and inventory details to AD. Added preview and apply modes, then scheduled weekly execution.',outcome:'A scheduled inventory sync supporting device visibility and mobile offboarding.'},
{title:'Scaling shared storage',category:'Infrastructure',className:'infrastructure',tags:'Nutanix · Windows Server · DFS',symbols:['DFS','→','8 TB'],summary:'Expand staff storage and move data through a planned migration.',challenge:'Staff shared storage was approaching capacity and needed room to grow.',approach:'Provisioned additional Nutanix-backed storage, prepared the Windows volume, and used Robocopy for the initial data transfer and a follow-up delta pass.',outcome:'Expanded capacity with a staged migration process for enterprise shared files.'},
{title:'Keeping employee lists in sync',category:'Automation',className:'automation',tags:'ManageEngine · API · PowerShell',symbols:['CSV','→','API'],summary:'Connect a scheduled mailbox report to an automated employee mailing list.',challenge:'Employee list membership needed to follow the current enabled-mailbox population.',approach:'Published the latest ManageEngine report to a consistent CSV path. Built a preview/apply sync to update Constant Contact list membership, with report-age validation and handling for unsubscribed contacts.',outcome:'A recurring process for maintaining employee list membership from a defined operational source.'},
{title:'Testing the next identity sync',category:'Infrastructure',className:'identity',tags:'Entra Cloud Sync · Active Directory',symbols:['AD','→','Cloud'],summary:'Validate a Cloud Sync pilot before a broader identity migration.',challenge:'A change in identity synchronization needed practical evidence about behavior and timing.',approach:'Used a scoped test OU to check attribute propagation, enable/disable behavior, and account linkage. Recorded outcomes to support migration planning.',outcome:'Pilot findings that inform synchronization scope and the next migration decision.'}
];
let filter='All';const grid=document.querySelector('#projects'),search=document.querySelector('#search'),dialog=document.querySelector('#project-dialog');
function render(){const q=search.value.toLowerCase().trim();grid.replaceChildren();const selected=projects.map((p,i)=>({...p,index:i})).filter(p=>(filter==='All'||p.category===filter)&&[p.title,p.summary,p.tags].join(' ').toLowerCase().includes(q));document.querySelector('#empty').hidden=selected.length>0;selected.forEach(p=>{const button=document.createElement('button');button.className='project-card';button.setAttribute('aria-label',`Read project: ${p.title}`);button.innerHTML=`<div class="project-art ${p.className}"><span class="art-tag">SYSTEMS IN PRACTICE</span><span class="art-index">0${p.index+1}</span><div class="diagram" aria-hidden="true"><span>${p.symbols[0]}</span><i>${p.symbols[1]}</i><span>${p.symbols[2]}</span></div></div><div class="project-body"><span class="category">${p.category}</span><h3>${p.title}</h3><p>${p.summary}</p><div class="project-bottom"><span>${p.tags}</span><span>View project ↗</span></div></div>`;button.addEventListener('click',()=>openProject(p));grid.append(button)});}
function openProject(p){document.querySelector('#dialog-category').textContent=p.category+' / PROJECT OVERVIEW';document.querySelector('#dialog-title').textContent=p.title;document.querySelector('#dialog-summary').textContent=p.summary;const content=document.querySelector('#dialog-content');content.replaceChildren();[['The challenge',p.challenge],['The approach',p.approach],['The result',p.outcome],['Tools',p.tags]].forEach(([title,text])=>{const h=document.createElement('h3');h.textContent=title;const paragraph=document.createElement('p');paragraph.textContent=text;content.append(h,paragraph)});dialog.showModal();}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active))});render()}));search.addEventListener('input',render);document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});render();
